services:
  mssql-buber:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql-buber
    ports:
      - "1733:1433"
    environment:
      MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - vol-buber-mssql-data:/var/opt/mssql/data
      - vol-buber-mssql-log:/var/opt/mssql/log
      - vol-buber-mssql-secrets:/var/opt/mssql/secrets

volumes:
  vol-buber-mssql-data:
  vol-buber-mssql-log:
  vol-buber-mssql-secrets: