services:
  mssql-buber:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql-buber
    ports:
      - 1433:1433
    env_file:
      - env-var.env
    volumes:
      - vol-buber-mssql-data:/var/opt/mssql/data
      - vol-buber-mssql-log:/var/opt/mssql/log
      - vol-buber-mssql-secrets:/var/opt/mssql/secrets

volumes:
  vol-buber-mssql-data:
    name: vol-buber-mssql-data
  vol-buber-mssql-log:
    name: vol-buber-mssql-log
  vol-buber-mssql-secrets:
    name: vol-buber-mssql-secrets